export const KNOWN_ZOTERO_PROPERTY_KEYS = [
  'abstractNote',
  'allTags',
  'authors',
  'bibliography',
  'citation-key',
  'citationKey',
  'citationkey',
  'citekey',
  'collections',
  'date',
  'dateAdded',
  'dateModified',
  'doi',
  'DOI',
  'firstAttachmentLink',
  'firstAttachmentZoteroLink',
  'hashTags',
  'itemKey',
  'itemType',
  'key',
  'lastExportDate',
  'lastImportDate',
  'libraryID',
  'pdfLink',
  'pdfZoteroLink',
  'publicationTitle',
  'publisher',
  'tags',
  'title',
  'url',
  'zotero_key',
  'zoteroAbstract',
  'zoteroAnnotationCount',
  'zoteroAuthors',
  'zoteroKey',
  'zoteroCollections',
  'zoteroCitekey',
  'zoteroCiteKey',
  'zoteroDateAdded',
  'zoteroDateModified',
  'zoteroDOI',
  'zoteroItemKey',
  'zoteroLibraryID',
  'zoteroNote',
  'zoteroOpenTaskCount',
  'zoteroOpenTasks',
  'zoteroOrphaned',
  'zoteroOrphanedCheckedAt',
  'zoteroOrphanedReason',
  'zoteroPDF',
  'zoteroProject',
  'zoteroPublication',
  'zoteroPublisher',
  'zoteroReader',
  'zoteroSciteCitingPublications',
  'zoteroSciteContradicting',
  'zoteroSciteMentioning',
  'zoteroSciteStatus',
  'zoteroSciteSupporting',
  'zoteroSciteTotalStatements',
  'zoteroSciteUnclassified',
  'zoteroSciteUpdatedAt',
  'zoteroSciteURL',
  'zoteroStatus',
  'zoteroSummary',
  'zoteroTags',
  'zoteroTitle',
  'zoteroTopic',
  'zoteroType',
  'zoteroURI',
  'zoteroURL',
  'zoteroYear',
];

export function getInvalidPreservedProperties(
  properties: readonly string[] | undefined,
  availableProperties: Iterable<string> = []
): string[] {
  if (!properties?.length) return [];

  const valid = new Set<string>([
    ...KNOWN_ZOTERO_PROPERTY_KEYS,
    ...Array.from(availableProperties),
  ]);

  return properties.filter((property) => !!property && !valid.has(property));
}
